import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans", // กำหนดฟอนต์ Geist Sans
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // กำหนดฟอนต์ Geist Mono
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"), // กำหนด base URL สำหรับ SEO
  title: "Notion CMS",
  description: "Generated by create next app",
  openGraph: {
    title: "Notion CMS",
    description: "Generated by create next app",
    url: "/",
    siteName: "Notion CMS",
    locale: "th_TH",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Notion CMS",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // โหลดฟอนต์และตั้งค่าเริ่มต้น
      >
        {children} {/* แรนเดอร์เนื้อหาหน้าเว็บลูก */}
      </body>
    </html>
  );
}
